apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: gcr.io/kuar-demo/kuard-amd64:1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi
    ports:
    - containerPort: 8080
      name: http
    livenessProbe:
      httpGet:
        path: /healthy
        port: 8080
      periodSeconds: 10
      initialDelaySeconds: 5
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      periodSeconds: 10
      initialDelaySeconds: 5
      failureThreshold: 3