apiVersion: v1
kind: Pod
metadata:
  name: app-volume
spec:
  containers:
  - name: app
    image: gcr.io/kuar-demo/kuard-amd64:1
    ports:
    - containerPort: 8080
      name: http
    livenessProbe:
      httpGet:
        path: /healthy
        port: 8080
      periodSeconds: 10
      initialDelaySeconds: 5
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      periodSeconds: 10
      initialDelaySeconds: 5
      failureThreshold: 3
  volumes:
  - name: data
    hostPath:
      path: /var/lib/app