apiVersion: v1
kind: Pod
metadata:
  name: app-multi-containers
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  - name: debian
    image: debian
    command: ["/bin/sh", "-c", "date > /html/index.html"]
    volumeMounts:
    - name: html
      mountPath: /html
  volumes:
  - name: html
    emptyDir: {}