apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: demo
    run: demo
spec:
  containers:
  - name: app
    image: gcr.io/shkirmantsev/demo:v1.0.0
    ports:
    - containerPort: 8000
      name: http